#!/usr/bin/env python3
"""
ai_client.py  ←  GENERATED by migrate_to_free_api.py
Single import point for AI calls. Switch provider by re-running the migrator.
Provider: gemini
"""

import os
import sys

_api_key = os.environ.get("GEMINI_API_KEY", "")
if not _api_key:
    print("❌ GEMINI_API_KEY environment variable is not set.", file=sys.stderr)
    sys.exit(1)

import google.generativeai as genai
genai.configure(api_key=_api_key)


def _llm(system: str, user: str, max_tokens: int = 1500) -> str:
    """Call Gemini 2.0 Flash (free tier)."""
    model = genai.GenerativeModel(
        model_name="gemini-2.0-flash",
        system_instruction=system,
    )
    try:
        response = model.generate_content(
            user,
            generation_config={"max_output_tokens": max_tokens},
        )
        return response.text
    except Exception as e:
        print(f"❌ Gemini API error: {e}", file=sys.stderr)
        raise


# Public API — all scripts call this
def generate(system: str, user: str, max_tokens: int = 1500) -> str:
    """Call the configured LLM. Returns the response text."""
    return _llm(system=system, user=user, max_tokens=max_tokens)
