#!/usr/bin/env python3
"""
migrate_to_free_api.py
Run this script once to swap all scripts from Anthropic → free API of your choice.

Usage:
    python scripts/migrate_to_free_api.py --provider gemini
    python scripts/migrate_to_free_api.py --provider github
    python scripts/migrate_to_free_api.py --provider groq
"""

import pathlib
import sys

PROVIDER = sys.argv[sys.argv.index("--provider") + 1] if "--provider" in sys.argv else "gemini"

# ── Shared call() function for each provider ──────────────────────────────────

GEMINI_HELPER = '''
import google.generativeai as genai as _genai
_genai.configure(api_key=os.environ["GEMINI_API_KEY"])

def _llm(system: str, user: str, max_tokens: int = 1500) -> str:
    """Call Gemini 2.0 Flash (free tier)."""
    model = _genai.GenerativeModel(
        model_name="gemini-2.0-flash",
        system_instruction=system,
    )
    response = model.generate_content(user)
    return response.text
'''

GITHUB_HELPER = '''
from openai import OpenAI as _OAI

def _llm(system: str, user: str, max_tokens: int = 1500) -> str:
    """Call GitHub Models via GITHUB_TOKEN (free, no extra secret needed)."""
    client = _OAI(
        base_url="https://models.inference.ai.azure.com",
        api_key=os.environ["GITHUB_TOKEN"],
    )
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        max_tokens=max_tokens,
    )
    return response.choices[0].message.content
'''

GROQ_HELPER = '''
from openai import OpenAI as _OAI

def _llm(system: str, user: str, max_tokens: int = 1500) -> str:
    """Call Groq Llama 3 (free tier: 14,400 req/day)."""
    client = _OAI(
        base_url="https://api.groq.com/openai/v1",
        api_key=os.environ["GROQ_API_KEY"],
    )
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        max_tokens=max_tokens,
    )
    return response.choices[0].message.content
'''

HELPERS = {
    "gemini": GEMINI_HELPER,
    "github": GITHUB_HELPER,
    "groq": GROQ_HELPER,
}

REQUIREMENTS = {
    "gemini": "google-generativeai>=0.8.0\nrequests>=2.31.0\npython-dotenv>=1.0.0\n",
    "github": "openai>=1.0.0\nrequests>=2.31.0\npython-dotenv>=1.0.0\n",
    "groq":   "openai>=1.0.0\nrequests>=2.31.0\npython-dotenv>=1.0.0\n",
}

ENV_VAR = {
    "gemini": "GEMINI_API_KEY",
    "github": "GITHUB_TOKEN",
    "groq":   "GROQ_API_KEY",
}

# ── The universal AI client wrapper ──────────────────────────────────────────

UNIVERSAL_CLIENT = f'''#!/usr/bin/env python3
"""
ai_client.py  ←  GENERATED by migrate_to_free_api.py
Single import point for AI calls. Switch provider by re-running the migrator.
Provider: {PROVIDER}
"""

import os
{HELPERS[PROVIDER]}

# Public API — all scripts call this
def generate(system: str, user: str, max_tokens: int = 1500) -> str:
    """Call the configured LLM. Returns the response text."""
    return _llm(system=system, user=user, max_tokens=max_tokens)
'''

# ── Write the client wrapper ──────────────────────────────────────────────────

client_path = pathlib.Path("scripts/ai_client.py")
client_path.write_text(UNIVERSAL_CLIENT)
print(f"✅ Created scripts/ai_client.py (provider: {PROVIDER})")

# ── Update requirements.txt ───────────────────────────────────────────────────

pathlib.Path("requirements.txt").write_text(REQUIREMENTS[PROVIDER])
print(f"✅ Updated requirements.txt for {PROVIDER}")

# ── Print workflow env update instructions ────────────────────────────────────

env_var = ENV_VAR[PROVIDER]

print(f"""
╔════════════════════════════════════════════════════════════════╗
║  Migration to {PROVIDER.upper()} complete!
╠════════════════════════════════════════════════════════════════╣
║
║  1. Update .github/workflows/daily-pulse.yml
║     Replace:  ANTHROPIC_API_KEY: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
║     With:     {env_var}: ${{{{ secrets.{env_var} }}}}
║
║  2. Add repo secret (skip if using github provider):
║     GitHub → Settings → Secrets → Actions → New secret
║     Name:  {env_var}
║     Value: your-api-key-here
║
║  3. Each script now imports from ai_client:
║     from ai_client import generate
║     result = generate(system="...", user="...")
║
║  FREE TIER LIMITS:
║  • Gemini: 1,500 req/day  ✅ (need 10/day)
║  • GitHub: ~150 req/day   ✅ (need 10/day)
║  • Groq:   14,400 req/day ✅ (need 10/day)
╚════════════════════════════════════════════════════════════════╝
""")

print("✅ Done! Run: python scripts/fetch_news.py to test.")
